### ISSUE TITLE
Elaborar documento de visão do projeto

### ISSUE THREAD

**Issue by lilialnas** [K0rgana/coleta-seletiva#1]
Eu como ***usuário coletor e usuário descartante***  preciso de uma explicação melhor sobre o projeto em um documento de texto para facilitar o entendimento da proposta.

- [x] Elaborar uma descrição do sistema onde fique claro o que o sistema visa atender.
- [x] Elaborar em conceito macro as funcionalidades do sistema
- [x] Prospectar quais tecnologias serão utilizadas no sistema
- [x] Definir equipe do projeto

Critério de aceitação: Todas as informações no README.md do repositório.

**Comment by simeiaolimpia** [comment]
GH-1< adiciona descrição do  #sistema>

**Comment by simeiaolimpia** [comment]
#  GH-1< adiciona a descrição do sistema >

**Comment by simeiaolimpia** [comment]
GH-1` adiciona descrição do  #sistema`

**Comment by simeiaolimpia** [comment]
# GH-1 ` adiciona descrição do  #sistema`

**Comment by simeiaolimpia** [comment]
GH-1` adiciona descrição do sistema `
